/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore
delete Element.prototype.classList;
// @ts-ignore
delete Element.prototype.closest;
// @ts-ignore
delete Element.prototype.matches;
// @ts-ignore
delete Element.prototype.after;
// @ts-ignore
delete Element.prototype.append;
// @ts-ignore
delete Element.prototype.before;
// @ts-ignore
delete Element.prototype.prepend;
// @ts-ignore
delete Element.prototype.remove;
// @ts-ignore
delete Element.prototype.replace;
